version: '3.9'

services:
  spring-batch-to-db:
    container_name: spring-batch-to-db
    image: gyawalirajiv/spring-batch-to-db
    ports:
      - 8080:8080
    volumes:
      - .:/batch/
    restart: always
    environment:
      MYSQL_URL: batch-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - batch-net
    depends_on:
      batch-mysql:
        condition: service_healthy

  batch-mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: swa
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    restart: on-failure
    networks:
      - batch-net
    volumes:
      - swa_batch_mysql:/var/lib/mysql

volumes:
  swa_batch_mysql:

networks:
  batch-net: