spring:
  application:
    name: swa
  datasource:
    password: pass
    url: jdbc:mysql://localhost:3306/swa?allowPublicKeyRetrieval=true&useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always